CC = gcc -g
AR= ar rc
RANLIB = ranlib
OCAMLC=/usr/bin/ocamlc.opt -g $(OFLAGS)
OCAMLOPT=/usr/bin/ocamlopt.opt $(OFLAGS)
OCAMLDEP=/usr/bin/ocamldep.opt
OCAMLLEX=/usr/bin/ocamllex.opt
OCAMLYACC=/usr/bin/ocamlyacc
OCAMLDOC=/usr/bin/ocamldoc.opt
OCAMLVERSION=3.09.2
OCAMLDIR=/usr/lib/ocaml/3.09.2
CP=cp -f


HTML_DIR=doc/html
MAN_DIR=doc/man
